name: team1flow
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - uses: actions/checkout@v3
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'      
      - run: az account show
        shell: bash
      - uses: tvdvoorde/action1@main
        with:
          input1: ${{ secrets.APPSECRET }}




