on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: tvdvoorde/action1@main
        with:
          input1: 'This is input 1'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

